import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import GlobalAccessMenu from "@/components/global/globalAccessMenu";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <Providers>
          {children}
          <div className="fixed top-[calc(5%-12px)] right-2 -mt-4">
          <GlobalAccessMenu />
          </div>
          </Providers>
      </body>
    </html>
  );
}
